### ISSUE TITLE
No enchantment support

### ISSUE THREAD

**Issue by daemon** [daemon/mcex-plugin#6]
Enchantments not preserved in trades.

**Comment by Siphonophore** [comment]
You could use an item metadata Map<> and store the item, along with it's metadata. Once a trade has occurred, the data out of the Map<> can be recalled and enchantment support can be added, along with other metadata such as wood values, and lore.

**Comment by daemon** [comment]
A cache for item ID-to-data could work like that. The problem here is that I'm not persisting enchantments to the database.

**Comment by Siphonophore** [comment]
Oh. You want to preserve the enchantments even after the server reloads?

**Comment by Siphonophore** [comment]
I suggest creating a separate section in the database for items that were to be traded, but couldn't because of some unexpected/expected event. Like, you could add the items that went missing in the database, along with their metadata. Like:

item_sword_(player):
  sword_type: diamond
  metadata:
    enchantment: SHARPNESS
    enchantment_level: 2
    name: <&6><&l>Sword of Evil's Bane
    lore: A legendary sword used by true heroes.
    price: 150
    players_involved: tetrisd, Varni1
    trading_for: cobblestone

**Comment by Siphonophore** [comment]
Otherwise, I can't think of any other solution.

**Comment by daemon** [comment]
Yeah, that's the general idea. I will create a table to store the enchantments and another table for item-to-enchantment associations.

I'm not sure what you mean by items that go missing.

**Comment by Siphonophore** [comment]
Well, for example, when a player is about to trade, and the server crashes, the database saves that trade data so neither parties can lose their items.

**Comment by daemon** [comment]
Oh. In most crash scenarios, the trades are guaranteed to be atomic. In a few edge cases however, the plugin will be biased toward players losing instead of gaining duplicate assets.
